name: build-deploy

on:
  push:
    branches: ["main"]
    paths-ignore: # 忽略的文件
      - "README.md"
      - "LICENSE"
      - "CHANGELOG.md"
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: home
  IMAGE_NAME_FULL: ghcr.io/nbtca/home

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master

      - name: Login DockerHub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          no-cache: true
          # target: deploy
          push: true
          platforms: linux/amd64
          tags: |
            ${{ env.IMAGE_NAME_FULL }}:latest

      - name: ssh pipelines
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.ACCESS_TOKEN }}
          script: |
            printenv
            cd ${{ secrets.REMOTE_PATH }}
            docker compose up --force-recreate -d
